In [1]:

import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.model_selection import train_test_split

In [4]:
df=pd.read_csv('HousingData.csv')

In [56]:
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,NaN,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,NaN,22.4
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.0,0.573,6.030,NaN,2.5050,1,273,21.0,396.90,7.88,11.9

In [57]:
df_x=df[['TAX']]
df_y = df[['MEDV']]

In [58]:
df_x.describe()

              TAX
count  506.000000
mean   408.237154
std    168.537116
min    187.000000
25%    279.000000
50%    330.000000
75%    666.000000
max    711.000000

In [59]:
reg = linear_model.LinearRegression()

In [60]:
x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size= 0.33, random_state= 42)

In [61]:
reg.fit(x_train, y_train)

LinearRegression()

In [62]:
print(reg.coef_)

[[-0.02542649]]

In [63]:
y_pred = reg.predict(x_test)
print(y_pred)

[[25.84736521]
 [26.91527785]
 [15.2953712 ]
 [25.61852678]
 [16.43956332]
 [23.25386307]
 [25.64395327]
 [22.26222989]
 [16.43956332]
 [23.43184851]
 [26.35589504]
 [25.46596783]
 [16.43956332]
 [23.25386307]
 [26.07620363]
 [16.43956332]
 [28.5934263 ]
 [16.43956332]
 [26.88985136]
 [16.43956332]
 [27.70349909]
 [26.91527785]
 [25.5676738 ]
 [26.43217451]
 [16.43956332]
 [16.43956332]
 [23.25386307]
 [16.43956332]
 [26.33046855]
 [23.43184851]
 [25.84736521]
 [26.07620363]
 [16.43956332]
 [16.43956332]
 [16.43956332]
 [23.12673061]
 [27.22039575]
 [27.6780726 ]
 [26.33046855]
 [25.61852678]
 [23.43184851]
 [27.72892558]
 [27.6780726 ]
 [24.60146712]
 [26.50845399]
 [16.43956332]
 [25.5676738 ]
 [25.61852678]
 [16.43956332]
 [25.84736521]
 [25.46596783]
 [27.88148453]
 [25.5676738 ]
 [23.60983395]
 [26.66101294]
 [16.43956332]
 [16.43956332]
 [27.14411628]
 [27.09326329]
 [24.98286449]
 [26.1524831 ]
 [27.62721962]
 [25.5676738 ]
 [25.5676738 ]
 [22.92331868]
 [26.33046855]
 [16.43956332]
 [26.22876258]
 [26.96613084]
 [16.43956332]
 [27.44923418]
 [16.43956332]
 [16.43956332]
 [24.88115853]
 [23.25386307]
 [16.43956332]
 [23.60983395]
 [27.6780726 ]
 [16.43956332]
 [15.2953712 ]
 [24.60146712]
 [16.43956332]
 [25.36426187]
 [16.43956332]
 [25.64395327]
 [25.5676738 ]
 [16.43956332]
 [26.07620363]
 [26.50845399]
 [22.26222989]
 [25.84736521]
 [16.43956332]
 [22.26222989]
 [24.42348168]
 [16.43956332]
 [22.26222989]
 [16.43956332]
 [16.43956332]
 [16.43956332]
 [16.43956332]
 [27.09326329]
 [23.25386307]
 [16.43956332]
 [25.5676738 ]
 [25.64395327]
 [16.43956332]
 [25.5676738 ]
 [26.07620363]
 [27.6780726 ]
 [25.41511485]
 [16.43956332]
 [16.43956332]
 [27.6780726 ]
 [28.46629384]
 [25.5676738 ]
 [16.43956332]
 [28.46629384]
 [25.5676738 ]
 [23.43184851]
 [25.74565924]
 [24.98286449]
 [24.98286449]
 [16.43956332]
 [22.38936235]
 [27.44923418]
 [26.07620363]
 [24.44890817]
 [28.46629384]
 [23.12673061]
 [27.88148453]
 [28.5934263 ]
 [22.44021534]
 [25.5676738 ]
 [22.38936235]
 [23.12673061]
 [16.43956332]
 [27.6780726 ]
 [26.86442487]
 [26.63558644]
 [25.5676738 ]
 [25.5676738 ]
 [24.27092273]
 [24.80487905]
 [26.33046855]
 [16.43956332]
 [26.50845399]
 [23.12673061]
 [16.43956332]
 [25.5676738 ]
 [25.5676738 ]
 [16.43956332]
 [16.43956332]
 [27.72892558]
 [22.38936235]
 [27.44923418]
 [25.5676738 ]
 [16.43956332]
 [16.43956332]
 [27.72892558]
 [16.43956332]
 [28.46629384]
 [26.1524831 ]
 [23.60983395]
 [26.07620363]
 [26.66101294]
 [25.5676738 ]
 [26.66101294]]

In [64]:
print(y_test)

     MEDV
173  23.6
274  32.4
491  13.6
72   22.8
452  16.1
..    ...
110  21.7
321  23.1
265  22.8
29   21.0
262  48.8

[167 rows x 1 columns]

In [65]:
print( np.mean((y_pred - y_test)**2 ))

MEDV    57.547077
dtype: float64

C:\ProgramData\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:3430: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)

In [66]:
from sklearn.metrics import mean_squared_error
print( mean_squared_error(y_test, y_pred))

57.547077436329005

In [67]:
from sklearn import metrics
mse = metrics.mean_squared_error(y_test,y_pred)
mae = metrics.mean_absolute_error(y_test,y_pred)
rmse = np.sqrt(metrics.mean_squared_error(y_test,y_pred))
print(f'Mean Squared Error: {mse}',f'Mean Absolute Error: {mae}',f'Root Mean Squared Error: {rmse}',sep='\n')

Mean Squared Error: 57.547077436329005
Mean Absolute Error: 5.691287422152499
Root Mean Squared Error: 7.58597900315635